"""Refresh `paper/results.tex` from `experiments/results/results.csv`.

Re-run after every full benchmark to keep the IEEE paper in sync with the
latest experimental numbers.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
RESULTS_CSV = ROOT / "experiments" / "results" / "results.csv"
STATS_JSON = ROOT / "experiments" / "results" / "stats.json"
OUT = ROOT / "paper" / "results.tex"

DETECTORS = ["adwin", "ddm", "eddm", "kswin", "page_hinkley", "hybrid"]
SHORT = {"adwin": "Adwin", "ddm": "DDM", "eddm": "EDDM",
         "kswin": "KSWIN", "page_hinkley": "PH", "hybrid": "Hybrid"}


def cmd(name: str, value: str) -> str:
    return f"\\newcommand{{\\{name}}}{{{value}}}\n"


def fmt(x: float, digits: int = 3) -> str:
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return "--"
    return f"{x:.{digits}f}"


def main() -> int:
    if not RESULTS_CSV.exists():
        print(f"missing {RESULTS_CSV}; run `python -m src.pipelines.experiment`", file=sys.stderr)
        return 1

    df = pd.read_csv(RESULTS_CSV)

    # Refuse to overwrite the bundled paper macros with a small smoke run.
    # The bundled values reflect a representative full benchmark; smaller runs
    # often invert the rankings due to short-stream artefacts.
    n_blocks_per_det = df.groupby("detector").size().min() if not df.empty else 0
    if n_blocks_per_det < 6:
        print(f"only {n_blocks_per_det} blocks per detector -- not enough to "
              f"refresh paper macros; run a fuller benchmark", file=sys.stderr)
        return 0
    elec = df[df["stream"] == "elec2"].groupby("detector")["accuracy"].mean()
    sea = df[df["stream"] == "sea"]
    delay = sea.groupby("detector")["mean_detection_delay"].mean()
    fp = sea.groupby("detector")["false_positive_rate"].mean()

    lines = ["% Auto-generated by scripts/fill_paper_numbers.py\n"]
    for d in DETECTORS:
        lines.append(cmd(f"AccElec{SHORT[d]}", fmt(elec.get(d, float('nan')))))
    for d in DETECTORS:
        lines.append(cmd(f"DelaySea{SHORT[d]}", fmt(delay.get(d, float('nan')), 0)))
    for d in DETECTORS:
        lines.append(cmd(f"FP{SHORT[d]}", fmt(fp.get(d, float('nan')), 2)))

    lat = df["latency_p99_us"].mean() / 1000.0 if "latency_p99_us" in df else float("nan")
    tput = df["throughput_samples_per_s"].mean() if "throughput_samples_per_s" in df else float("nan")
    lines.append(cmd("LatPnn", fmt(lat, 2)))
    lines.append(cmd("Throughput", fmt(tput, 0)))

    p_val = "n/a"
    cd_val = "n/a"
    if STATS_JSON.exists():
        stats = json.loads(STATS_JSON.read_text())
        acc = stats.get("accuracy", {})
        if acc.get("applicable"):
            p_val = fmt(acc.get("friedman_p"), 4)
            cd_val = fmt(acc.get("critical_difference"), 2)
    lines.append(cmd("FriedmanP", p_val))
    lines.append(cmd("CritDiff", cd_val))

    OUT.write_text("".join(lines))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
